services:
  zipper:
    container_name: "zipper"
    #build: .
    image: ashishwayachal12/zipper:latest
    restart: always
    ports:
      - "1111:80"
    volumes:
      - "zipper-vol:/usr/share/nginx/html"
    networks:
      - "zipper-net"

volumes:
  zipper-vol:
    name: "zipper-vol"

networks:
  zipper-net:
    name: "zipper-net"

